// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdSNA0SJqfdyFNLJlX24s1gEHhBu4UOj0',
    appId: '1:994771192874:web:cbe69bb6adc6f365f94753',
    messagingSenderId: '994771192874',
    projectId: 'nursinghomecare-1807f',
    authDomain: 'nursinghomecare-1807f.firebaseapp.com',
    storageBucket: 'nursinghomecare-1807f.firebasestorage.app',
    measurementId: 'G-SF05KK6248',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4gblm7xZ6DeOP1mHZVHMDQSKitBUd00U',
    appId: '1:994771192874:android:67e0bc9ee4d9a042f94753',
    messagingSenderId: '994771192874',
    projectId: 'nursinghomecare-1807f',
    storageBucket: 'nursinghomecare-1807f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdbDgLoFIZ-b-vPLFGrnrPvFZJxYrc-3s',
    appId: '1:994771192874:ios:1fd1672d58bddb2af94753',
    messagingSenderId: '994771192874',
    projectId: 'nursinghomecare-1807f',
    storageBucket: 'nursinghomecare-1807f.firebasestorage.app',
    iosBundleId: 'com.example.firstv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqQx8jQd9vKxL8OX5WQJ-9pYvKq3zP5mM',
    appId: '1:994771192874:ios:abc123def456ghi789',
    messagingSenderId: '994771192874',
    projectId: 'nursinghomecare-1807f',
    storageBucket: 'nursinghomecare-1807f.appspot.com',
    iosBundleId: 'com.example.firstv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqQx8jQd9vKxL8OX5WQJ-9pYvKq3zP5mM',
    appId: '1:994771192874:web:abc123def456ghi789',
    messagingSenderId: '994771192874',
    projectId: 'nursinghomecare-1807f',
    authDomain: 'nursinghomecare-1807f.firebaseapp.com',
    storageBucket: 'nursinghomecare-1807f.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );
}